#!/usr/bin/env bash
# compare.sh — run the SAME task through every AVAILABLE harness adapter on the
# SAME rules-based verifier, and tabulate iterations / wall-time / result.
#
# This is the "test & compare the best one" step: the verifier is identical across
# adapters, so the only variable is the harness. Adapters that aren't installed are
# skipped honestly (and noted), so the table only ever reports what actually ran.
#
# Usage:
#   ./compare.sh                 # mock + ollama (offline, free)
#   RUN_CLAUDE=1 ./compare.sh    # also run claude -p (spends tokens)
#
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
TASK="tasks/hello-sum"
OUT="results/comparison.md"
mkdir -p results

# --- decide which adapters can actually run right now -------------------------
adapters=()
notes=()

adapters+=("mock");   notes+=("mock|deterministic offline baseline")

if curl -s "${OLLAMA_HOST:-http://localhost:11434}/api/tags" >/dev/null 2>&1; then
  adapters+=("ollama"); notes+=("ollama|REAL local model (${OLLAMA_MODEL:-qwen3:8b}), offline, \$0")
else
  notes+=("ollama|SKIPPED — ollama server not reachable")
fi

if [ "${RUN_CLAUDE:-0}" = "1" ] && command -v claude >/dev/null 2>&1; then
  adapters+=("claude"); notes+=("claude|REAL Claude Code headless (spends tokens)")
else
  notes+=("claude|SKIPPED — set RUN_CLAUDE=1 (spends tokens) and install claude")
fi

if command -v hermes >/dev/null 2>&1; then
  adapters+=("hermes"); notes+=("hermes|REAL Hermes Agent headless")
else
  notes+=("hermes|SKIPPED — not installed (see LEARNINGS.md 'Wiring Hermes live')")
fi

# --- run each available adapter and collect result.json -----------------------
rows=()
for a in "${adapters[@]}"; do
  echo ">>> running adapter: $a"
  ./loop.sh "$TASK" "$a" 5 || true
  rj=".runs/$(basename "$TASK").$a/result.json"
  if [ -f "$rj" ]; then
    read -r res iters wall <<<"$(jq -r '[.result,.iterations,.wall_ms]|@tsv' "$rj")"
    rows+=("$a|$res|$iters|${wall}")
  else
    rows+=("$a|no-result|-|-")
  fi
  echo
done

# --- write the markdown comparison --------------------------------------------
{
  echo "# Harness comparison — task: \`hello-sum\` (fix a one-line bug until \`node --test\` passes)"
  echo
  echo "Same verifier (\`tasks/hello-sum/verify.sh\`) for every row. Only the harness changes."
  echo "Generated by \`compare.sh\`."
  echo
  echo "| Harness | Result | Iterations | Wall time | Cost | Offline |"
  echo "|---------|--------|-----------:|----------:|------|:-------:|"
  for r in "${rows[@]}"; do
    IFS='|' read -r a res iters wall <<<"$r"
    case "$a" in
      mock)   cost="\$0 (no model)"; off="✅";;
      ollama) cost="\$0 (local)";    off="✅";;
      claude) cost="tokens";         off="❌";;
      hermes) cost="tokens or \$0 local"; off="✅*";;
      *)      cost="?";              off="?";;
    esac
    wall_disp="$wall"; [ "$wall" != "-" ] && wall_disp="${wall} ms"
    printf "| %s | %s | %s | %s | %s | %s |\n" "$a" "$res" "$iters" "$wall_disp" "$cost" "$off"
  done
  echo
  echo "_✅\\* Hermes is offline-capable when pointed at a local model endpoint._"
  echo
  echo "## Adapter availability this run"
  for n in "${notes[@]}"; do IFS='|' read -r a d <<<"$n"; echo "- **$a** — $d"; done
} > "$OUT"

echo "================ comparison ================"
cat "$OUT"
echo "(written to $OUT)"
