#!/usr/bin/env bash
# compare.sh — run one or more tasks through every AVAILABLE harness adapter on
# the SAME rules-based verifier, and tabulate result / iterations / wall / tokens
# / cost. The verifier is identical across adapters for a given task, so the only
# variable is the harness. Adapters that can't run right now are skipped honestly.
#
# Usage:
#   ./compare.sh                       # default battery (every tasks/*/ with verify.sh)
#   ./compare.sh tasks/research-deck   # one or more specific task dirs
#   RUN_CLAUDE=1 ./compare.sh          # also run `claude -p` (spends tokens)
#
# Notes:
#   - mock is the sum.js-specific baseline; it only applies to tasks/hello-sum.
#   - ollama runs iff its server is reachable; claude runs iff RUN_CLAUDE=1 + installed.
#   - Per-row Cost is priced from pricing.json; `node cost.js` gives the full ledger.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
OUT="results/comparison.md"
mkdir -p results

# --- tasks: args, or every tasks/*/ that has a verify.sh ----------------------
TASKS=("$@")
if [ ${#TASKS[@]} -eq 0 ]; then
  for d in tasks/*/; do [ -f "${d}verify.sh" ] && TASKS+=("${d%/}"); done
fi

# --- adapter availability -----------------------------------------------------
ollama_up=0
curl -s "${OLLAMA_HOST:-http://localhost:11434}/api/tags" >/dev/null 2>&1 && ollama_up=1
claude_ok=0
[ "${RUN_CLAUDE:-0}" = "1" ] && command -v claude >/dev/null 2>&1 && claude_ok=1

adapters_for() {  # which adapters apply to a given task
  local name; name="$(basename "$1")"
  [ "$name" = "hello-sum" ] && echo "mock"   # mock is the sum.js-specific baseline
  [ "$ollama_up" = "1" ] && echo "ollama"
  [ "$claude_ok" = "1" ] && echo "claude"
}

cost_of() {  # <adapter> <tok_in> <tok_out> -> "$0" or "$0.0123"
  node -e '
    const p=require("./pricing.json");
    const m=p.adapterModel[process.argv[1]]||"ollama/qwen3:8b";
    const pr=p.models[m]||{in:0,out:0};
    const usd=((+process.argv[2]||0)*pr.in+(+process.argv[3]||0)*pr.out)/1e6;
    process.stdout.write(usd===0 ? "$0" : ("$"+usd.toFixed(4)));
  ' "$1" "$2" "$3"
}

# --- run + tabulate (write incrementally; progress to stderr) -----------------
: > "$OUT"
{
  echo "# Harness comparison"
  echo
  echo "One rules-based verifier per task; only the harness changes. Generated by \`compare.sh\`."
  echo "Offline column: ✅ = no off-box network / \$0 marginal."
  echo
} >> "$OUT"

for task in "${TASKS[@]}"; do
  name="$(basename "$task")"
  echo ">>> task: $name" >&2
  {
    echo "## \`$name\`"
    echo
    echo "| Harness | Result | Iters | Wall | tok in/out | Cost | Offline |"
    echo "|---------|--------|------:|-----:|-----------:|------|:-------:|"
  } >> "$OUT"

  while IFS= read -r a; do
    [ -z "$a" ] && continue
    echo "    - adapter: $a ..." >&2
    ./loop.sh "$task" "$a" 5 >/dev/null 2>&1 || true
    rj=".runs/$name.$a/result.json"
    if [ -f "$rj" ]; then
      read -r res iters wall tin tout <<<"$(jq -r '[.result,.iterations,.wall_ms,.tokens_in,.tokens_out]|@tsv' "$rj")"
    else
      res="no-result"; iters="-"; wall="-"; tin=0; tout=0
    fi
    case "$a" in claude) off="❌";; *) off="✅";; esac
    cost="$(cost_of "$a" "$tin" "$tout")"
    printf "| %s | %s | %s | %s ms | %s/%s | %s | %s |\n" \
      "$a" "$res" "$iters" "$wall" "$tin" "$tout" "$cost" "$off" >> "$OUT"
  done < <(adapters_for "$task")
  echo >> "$OUT"
done

{
  echo "## Adapter availability this run"
  echo "- **mock** — deterministic sum.js baseline (applies to \`hello-sum\` only)."
  if [ "$ollama_up" = "1" ]; then
    echo "- **ollama** — REAL local model (\`${OLLAMA_MODEL:-qwen3:8b}\`), offline, \$0 marginal."
  else
    echo "- **ollama** — SKIPPED (server not reachable at ${OLLAMA_HOST:-http://localhost:11434})."
  fi
  if [ "$claude_ok" = "1" ]; then
    echo "- **claude** — REAL Claude Code headless (\`claude -p\`, priced as claude-opus-4-8; spends tokens)."
  else
    echo "- **claude** — SKIPPED (set RUN_CLAUDE=1 and install claude to include it)."
  fi
  echo "- **hermes / nemo** — not installed (see LEARNINGS.md)."
} >> "$OUT"

echo "================ comparison ================"
cat "$OUT"
echo
echo "(written to $OUT — run \`node cost.js\` for the full priced ledger)"
