#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (countdown-game) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IHJlLCBwYXRobGliLCBzeXMKcCA9IHBhdGhsaWIuUGF0aCgnb3V0cHV0LnR4dCcpCmlmIG5vdCBwLmV4aXN0cygpOiBwcmludCgnb3V0cHV0LnR4dCBtaXNzaW5nJyk7IHN5cy5leGl0KDEpCmV4cHIgPSBwLnJlYWRfdGV4dCgpLnN0cmlwKCkKQUxMT1dFRCA9IFszLCA4LCAxMSwgMTksIDI1LCA3NV07IFRBUkdFVCA9IDQ2MgppZiBub3QgZXhwciBvciBub3QgYWxsKGNoIGluIHNldCgnMDEyMzQ1Njc4OSstKi8oKSAnKSBmb3IgY2ggaW4gZXhwcik6CiAgICBwcmludCgnaW52YWxpZCBjaGFyYWN0ZXJzIGluIGV4cHJlc3Npb24nKTsgc3lzLmV4aXQoMSkKdXNlZCA9IGxpc3QobWFwKGludCwgcmUuZmluZGFsbChyJ1xkKycsIGV4cHIpKSkKZm9yIG4gaW4gdXNlZDoKICAgIGlmIG4gbm90IGluIEFMTE9XRUQ6IHByaW50KCdudW1iZXIgbm90IGFsbG93ZWQ6Jywgbik7IHN5cy5leGl0KDEpCiAgICBpZiB1c2VkLmNvdW50KG4pID4gMTogcHJpbnQoJ251bWJlciB1c2VkIG1vcmUgdGhhbiBvbmNlOicsIG4pOyBzeXMuZXhpdCgxKQp0cnk6CiAgICB2ID0gZXZhbChleHByKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBwcmludCgnY2Fubm90IGV2YWw6JywgZSk7IHN5cy5leGl0KDEpCnN5cy5leGl0KDAgaWYgdiA9PSBUQVJHRVQgZWxzZSAocHJpbnQoJ2dvdCcsIHYsICd3YW50JywgVEFSR0VUKSBvciAxKSkK
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import re' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
