#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (recover-obfuscated-files) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IHBhdGhsaWIsIHN5cwpSRUNPVkVSWSA9IHBhdGhsaWIuUGF0aCgncmVjb3ZlcmVkJykKZXhwZWN0ZWRfZmlsZXMgPSB7CiAgICAicHJvamVjdF9hbHBoYS5sb2ciOiAoIkxvZyBlbnRyeSAxOiBTeXN0ZW0gaW5pdGlhbGl6ZWQuXG4iCiAgICAgICAgIkxvZyBlbnRyeSAyOiBVc2VyICdhZG1pbicgbG9nZ2VkIGluLlxuIgogICAgICAgICJMb2cgZW50cnkgMzogQ3JpdGljYWwgb3BlcmF0aW9uIHN0YXJ0ZWQuXG4iKSwKICAgICJjcmVkZW50aWFscy50eHQiOiAoInVzZXI6IHRlc3RfdXNlclxucGFzczogUDAkJHdPcmQxMjMhXG5zZXJ2ZXI6IDE5Mi4xNjguMS4xMDBcbiIpLAp9CmlmIG5vdCBSRUNPVkVSWS5pc19kaXIoKTogcHJpbnQoJ3JlY292ZXJlZC8gZGlyIG1pc3NpbmcnKTsgc3lzLmV4aXQoMSkKZXJycyA9IFtdCmZvciBuYW1lLCBjb250ZW50IGluIGV4cGVjdGVkX2ZpbGVzLml0ZW1zKCk6CiAgICBmcCA9IFJFQ09WRVJZIC8gbmFtZQogICAgaWYgbm90IGZwLmV4aXN0cygpOiBlcnJzLmFwcGVuZCgnbWlzc2luZyAnICsgbmFtZSk7IGNvbnRpbnVlCiAgICBpZiBmcC5yZWFkX3RleHQoKS5yZXBsYWNlKCdcclxuJywgJ1xuJykgIT0gY29udGVudDoKICAgICAgICBlcnJzLmFwcGVuZCgnYmFkIGNvbnRlbnQgJyArIG5hbWUpCmV4dHJhID0ge2YubmFtZSBmb3IgZiBpbiBSRUNPVkVSWS5pdGVyZGlyKCkgaWYgZi5pc19maWxlKCl9IC0gc2V0KGV4cGVjdGVkX2ZpbGVzKSAtIHsnLmdpdGtlZXAnfQppZiBleHRyYTogZXJycy5hcHBlbmQoJ2V4dHJhIGZpbGVzOiAnICsgJywgJy5qb2luKHNvcnRlZChleHRyYSkpKQppZiBlcnJzOiBwcmludCgnOyAnLmpvaW4oZXJycykpOyBzeXMuZXhpdCgxKQpzeXMuZXhpdCgwKQo=
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import pathlib' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
