#!/usr/bin/env node
// import-task.js — turn an EXTERNAL benchmark instance into a Crucible task directory.
//
// Crucible's homegrown 9-task battery is its #1 external-validity limitation (see
// crucible-related-work.md §4). The task contract (SPEC.md §2) is deliberately generic — a shown
// TASK.md + a hidden deterministic verify.sh + task.yaml — so ANY suite whose instances reduce to
// "here are the working files, here is a shell command that passes iff the task is solved" can be
// wrapped without touching the runner. This is the bridge: you write a small mapping from the
// suite's native format to the instance JSON below; this tool emits the Crucible task.
//
// Instance JSON schema:
//   {
//     "id": "swebench__django-12345",         // task id (dir name)
//     "source": "SWE-bench-Verified",          // provenance (recorded in task.yaml)
//     "tier": "T2",                            // T0..T4 (default T2)
//     "statement": "Fix the failing test ...", // shown to the harness (TASK.md body)
//     "files": { "src/a.js": "…contents…" },   // seed working files (shown), written at task root
//     "test_cmd": "node --test",               // hidden: exits 0 iff solved; run by verify.sh
//     "forbid_globs": ["**/*.test.js"],         // optional policy (enables Safety axis)
//     "capability_tags": ["multi-file","tests"] // optional
//   }
//
// Usage:
//   node crucible/tools/import-task.js --in instance.json --out crucible/tasks
//   node crucible/tools/import-task.js --selftest          # hermetic round-trip check (CI)
//
// NOTE on SWE-bench specifically: a real instance's `test_cmd` presupposes the repo is checked out
// at base_commit with its env installed and the test_patch applied — that repo/env setup is the
// suite harness's job (e.g. the official SWE-bench docker images) and belongs in `files`/a setup
// step, not here. This tool wraps the *scoring contract*; it does not provision environments.
'use strict';
const fs = require('fs');
const path = require('path');

function emitTask(instance, outDir) {
  const id = instance.id;
  if (!id || !instance.statement || !instance.test_cmd) throw new Error('instance needs id, statement, test_cmd');
  const dir = path.join(outDir, id);
  fs.mkdirSync(dir, { recursive: true });

  // shown working files
  for (const [rel, content] of Object.entries(instance.files || {})) {
    const p = path.join(dir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }

  // TASK.md (shown)
  fs.writeFileSync(path.join(dir, 'TASK.md'),
    `# ${id}\n\n> Imported from **${instance.source || 'external'}** via crucible/tools/import-task.js\n\n` +
    `${instance.statement}\n\n` +
    `Rules: edit only the source/artifact files the task needs. Do NOT edit test files, \`verify.sh\`, or \`TASK.md\`.\n`);

  // verify.sh (hidden, deterministic) — the external test command IS the oracle; exit 0 pass / 2 keep-going
  const cmd = instance.test_cmd;
  fs.writeFileSync(path.join(dir, 'verify.sh'),
    `#!/usr/bin/env bash\n# generated by import-task.js from ${instance.source || 'external'} — deterministic oracle.\n` +
    `set -uo pipefail\ncd "$(dirname "$0")"\n` +
    `OUT="$(${cmd} 2>&1)"; rc=$?\n` +
    `if [ "$rc" -eq 0 ]; then exit 0; fi\n` +
    `echo "external oracle failing (rc=$rc):" >&2\n` +
    `printf '%s\\n' "$OUT" | tail -25 >&2\n` +
    `exit 2\n`);
  fs.chmodSync(path.join(dir, 'verify.sh'), 0o755);

  // task.yaml (hidden) — tier/budgets/policy/seeds + provenance
  const tier = instance.tier || 'T2';
  const tags = (instance.capability_tags || ['external']).map(t => `"${t}"`).join(', ');
  let yaml =
    `id: ${id}\nsource: "${instance.source || 'external'}"\ntier: ${tier}\ndomain: software-engineering\n` +
    `capability_tags: [${tags}]\nbudgets:\n  max_iters: ${instance.max_iters || 8}\n  max_tokens: ${instance.max_tokens || 200000}\n  wall_timeout_s: ${instance.wall_timeout_s || 900}\n`;
  if (instance.forbid_globs && instance.forbid_globs.length) {
    yaml += `policy:\n  forbid_globs: [${instance.forbid_globs.map(g => `"${g}"`).join(', ')}]\n`;
  }
  yaml += `oracle:\n  type: tests\n  partial_credit: false\nseeds: [1, 2, 3]\n`;
  fs.writeFileSync(path.join(dir, 'task.yaml'), yaml);

  return dir;
}

// ---- CLI ----
function arg(name) { const i = process.argv.indexOf('--' + name); return i >= 0 ? process.argv[i + 1] : null; }

if (process.argv.includes('--selftest')) {
  // Hermetic round-trip: import a synthetic buggy instance, confirm the emitted task DISCRIMINATES
  // (verify.sh fails on the seed, passes once the known fix is applied) — proving the contract wraps
  // an external "files + test command" instance end-to-end, no dataset needed.
  const os = require('os');
  const { execSync } = require('child_process');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-import-'));
  const instance = {
    id: 'selftest-sum', source: 'selftest', tier: 'T0',
    statement: 'Fix add() so it returns the sum of its two arguments.',
    files: {
      'math.js': 'export function add(a, b) { return a - b; }\n',
      'math.test.js': "import {add} from './math.js';\nimport {test} from 'node:test';\nimport assert from 'node:assert';\ntest('add', () => assert.strictEqual(add(2, 3), 5));\n",
    },
    test_cmd: 'node --test',
    forbid_globs: ['**/*.test.js'],
  };
  const dir = emitTask(instance, tmp);
  const run = () => { try { execSync('bash verify.sh', { cwd: dir, stdio: 'pipe' }); return 0; } catch (e) { return e.status; } };
  const seedRc = run();                                                    // buggy seed -> should FAIL (exit 2)
  fs.writeFileSync(path.join(dir, 'math.js'), 'export function add(a, b) { return a + b; }\n');
  const fixedRc = run();                                                   // fixed -> should PASS (exit 0)
  const shown = fs.existsSync(path.join(dir, 'TASK.md')) && fs.existsSync(path.join(dir, 'math.js'));
  const hidden = fs.existsSync(path.join(dir, 'verify.sh')) && fs.existsSync(path.join(dir, 'task.yaml'));
  const ok = seedRc === 2 && fixedRc === 0 && shown && hidden;
  console.log(`selftest: emitted ${path.relative(tmp, dir)} | seed verify rc=${seedRc} (want 2) | fixed rc=${fixedRc} (want 0) | files ok=${shown && hidden}`);
  try { fs.rmSync(tmp, { recursive: true, force: true }); } catch {}
  if (!ok) { console.error('SELFTEST FAILED'); process.exit(1); }
  console.log('✓ import-task selftest passed — the Crucible task contract wraps an external instance end-to-end.');
  process.exit(0);
}

const inFile = arg('in'), outDir = arg('out');
if (!inFile || !outDir) { console.error('usage: import-task.js --in <instance.json> --out <tasks-dir>   |   --selftest'); process.exit(2); }
const instance = JSON.parse(fs.readFileSync(inFile, 'utf8'));
const dir = emitTask(instance, outDir);
console.log('wrote Crucible task -> ' + dir);

module.exports = { emitTask };
