#!/usr/bin/env node
// import-task.js — turn an EXTERNAL benchmark instance into a Crucible task directory.
//
// Crucible's homegrown 9-task battery is its #1 external-validity limitation (see
// crucible-related-work.md §4). The task contract (SPEC.md §2) is deliberately generic — a shown
// TASK.md + a hidden deterministic verify.sh + task.yaml — so ANY suite whose instances reduce to
// "here are the working files, here is a shell command that passes iff the task is solved" can be
// wrapped without touching the runner. This is the bridge: you write a small mapping from the
// suite's native format to the instance JSON below; this tool emits the Crucible task.
//
// Instance JSON schema:
//   {
//     "id": "swebench__django-12345",         // task id (dir name)
//     "source": "SWE-bench-Verified",          // provenance (recorded in task.yaml)
//     "tier": "T2",                            // T0..T4 (default T2)
//     "statement": "Fix the failing test ...", // shown to the harness (TASK.md body)
//     "files": { "src/a.js": "…contents…" },   // seed working files (shown), written at task root
//     "dirs": ["recovered"],                    // optional empty dirs to pre-create (shown)
//     "test_cmd": "node --test",               // hidden oracle: shell cmd, exits 0 iff solved
//     "check_py": "assert ...\n",               // hidden oracle: Python source (alt to test_cmd)
//     "forbid_globs": ["**/*.test.js"],         // optional policy (enables Safety axis)
//     "capability_tags": ["multi-file","tests"] // optional
//   }
//
// ORACLE (pick ONE): `test_cmd` is a shell command; `check_py` is Python source. Either runs with
// CWD = the disposable workdir root (so external "/app/…" paths must be rewritten to task-relative).
// Both are baked INTO verify.sh — which loop.sh keeps hidden and restores from the pristine task
// before every gate — so the agent can neither read nor edit the oracle. check_py is base64-embedded
// (never lands on disk as an importable/gameable *.py) and run through the first python3 on PATH that
// imports its modules; a stdlib-only checker therefore runs even under the launchd job's lean PATH.
//
// Usage:
//   node crucible/tools/import-task.js --in instance.json --out crucible/tasks
//   node crucible/tools/import-task.js --selftest          # hermetic round-trip check (CI)
//
// NOTE on SWE-bench specifically: a real instance's `test_cmd` presupposes the repo is checked out
// at base_commit with its env installed and the test_patch applied — that repo/env setup is the
// suite harness's job (e.g. the official SWE-bench docker images) and belongs in `files`/a setup
// step, not here. This tool wraps the *scoring contract*; it does not provision environments.
'use strict';
const fs = require('fs');
const path = require('path');

function emitTask(instance, outDir) {
  const id = instance.id;
  if (!id || !instance.statement) throw new Error('instance needs id, statement');
  if (!instance.test_cmd && !instance.check_py) throw new Error('instance needs test_cmd or check_py (the oracle)');
  if (instance.test_cmd && instance.check_py) throw new Error('give exactly one oracle: test_cmd OR check_py');
  const dir = path.join(outDir, id);
  fs.mkdirSync(dir, { recursive: true });

  // shown working files
  for (const [rel, content] of Object.entries(instance.files || {})) {
    const p = path.join(dir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }
  // shown empty dirs (e.g. an output/ the task tells the agent to populate). Marked with a
  // .gitkeep so the tree survives git — loop.sh restores task.yaml/verify.sh/*.test.js, not seeds.
  for (const rel of instance.dirs || []) {
    fs.mkdirSync(path.join(dir, rel), { recursive: true });
    fs.writeFileSync(path.join(dir, rel, '.gitkeep'), '');
  }

  // TASK.md (shown)
  fs.writeFileSync(path.join(dir, 'TASK.md'),
    `# ${id}\n\n> Imported from **${instance.source || 'external'}** via crucible/tools/import-task.js\n\n` +
    `${instance.statement}\n\n` +
    `Rules: edit only the source/artifact files the task needs. Do NOT edit test files, \`verify.sh\`, or \`TASK.md\`.\n`);

  // verify.sh (hidden, deterministic) — the external oracle IS the gate; exit 0 pass / 2 keep-going.
  const head = `#!/usr/bin/env bash\n# generated by import-task.js from ${instance.source || 'external'} — deterministic oracle.\n` +
    `set -uo pipefail\ncd "$(dirname "$0")"\n`;
  const tail = `if [ "$rc" -eq 0 ]; then exit 0; fi\n` +
    `echo "external oracle failing (rc=$rc):" >&2\n` +
    `printf '%s\\n' "$OUT" | tail -25 >&2\n` +
    `exit 2\n`;
  let body;
  if (instance.check_py != null) {
    // Embed the Python oracle base64 so it never lands on disk as an importable/editable file.
    // Pick the first python3 on PATH that can import the checker's own modules (imports lifted from
    // its `import`/`from` lines) — a stdlib-only checker then runs even under a lean launchd PATH.
    const b64 = Buffer.from(instance.check_py, 'utf8').toString('base64');
    const mods = [...new Set([...instance.check_py.matchAll(/^\s*(?:import|from)\s+([A-Za-z_][\w]*)/gm)]
      .map(m => m[1]).filter(m => m !== '__future__'))];
    const importProbe = mods.length ? `import ${mods.join(', ')}` : 'pass';
    body =
      `SRC=$(cat <<'__B64__'\n${b64}\n__B64__\n)\n` +
      `PYBIN=""\n` +
      `for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; ` +
      `"$c" -c '${importProbe}' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done\n` +
      `[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }\n` +
      `OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?\n`;
  } else {
    body = `OUT="$(${instance.test_cmd} 2>&1)"; rc=$?\n`;
  }
  fs.writeFileSync(path.join(dir, 'verify.sh'), head + body + tail);
  fs.chmodSync(path.join(dir, 'verify.sh'), 0o755);

  // task.yaml (hidden) — tier/budgets/policy/seeds + provenance
  const tier = instance.tier || 'T2';
  const tags = (instance.capability_tags || ['external']).map(t => `"${t}"`).join(', ');
  let yaml =
    `id: ${id}\nsource: "${instance.source || 'external'}"\ntier: ${tier}\ndomain: software-engineering\n` +
    `capability_tags: [${tags}]\nbudgets:\n  max_iters: ${instance.max_iters || 8}\n  max_tokens: ${instance.max_tokens || 200000}\n  wall_timeout_s: ${instance.wall_timeout_s || 900}\n`;
  if (instance.forbid_globs && instance.forbid_globs.length) {
    yaml += `policy:\n  forbid_globs: [${instance.forbid_globs.map(g => `"${g}"`).join(', ')}]\n`;
  }
  yaml += `oracle:\n  type: tests\n  partial_credit: false\nseeds: [1, 2, 3]\n`;
  fs.writeFileSync(path.join(dir, 'task.yaml'), yaml);

  return dir;
}

// ---- CLI ----
function arg(name) { const i = process.argv.indexOf('--' + name); return i >= 0 ? process.argv[i + 1] : null; }

if (require.main !== module) { module.exports = { emitTask }; return; }

if (process.argv.includes('--selftest')) {
  // Hermetic round-trip: import a synthetic buggy instance, confirm the emitted task DISCRIMINATES
  // (verify.sh fails on the seed, passes once the known fix is applied) — proving the contract wraps
  // an external "files + test command" instance end-to-end, no dataset needed.
  const os = require('os');
  const { execSync } = require('child_process');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'crucible-import-'));
  const instance = {
    id: 'selftest-sum', source: 'selftest', tier: 'T0',
    statement: 'Fix add() so it returns the sum of its two arguments.',
    files: {
      'math.js': 'export function add(a, b) { return a - b; }\n',
      'math.test.js': "import {add} from './math.js';\nimport {test} from 'node:test';\nimport assert from 'node:assert';\ntest('add', () => assert.strictEqual(add(2, 3), 5));\n",
    },
    test_cmd: 'node --test',
    forbid_globs: ['**/*.test.js'],
  };
  const dir = emitTask(instance, tmp);
  const run = () => { try { execSync('bash verify.sh', { cwd: dir, stdio: 'pipe' }); return 0; } catch (e) { return e.status; } };
  const seedRc = run();                                                    // buggy seed -> should FAIL (exit 2)
  fs.writeFileSync(path.join(dir, 'math.js'), 'export function add(a, b) { return a + b; }\n');
  const fixedRc = run();                                                   // fixed -> should PASS (exit 0)
  const shown = fs.existsSync(path.join(dir, 'TASK.md')) && fs.existsSync(path.join(dir, 'math.js'));
  const hidden = fs.existsSync(path.join(dir, 'verify.sh')) && fs.existsSync(path.join(dir, 'task.yaml'));

  // Second round-trip: the check_py oracle path (base64-embedded Python + empty output dir), proving
  // the hidden-Python bridge discriminates AND that the oracle source never lands on disk as a file.
  const pyInst = {
    id: 'selftest-py', source: 'selftest', tier: 'T0',
    statement: 'Write the answer 42 to out/answer.txt.',
    dirs: ['out'],
    check_py: "import pathlib, sys\np = pathlib.Path('out/answer.txt')\nsys.exit(0 if p.exists() and p.read_text().strip() == '42' else 1)\n",
  };
  const pdir = emitTask(pyInst, tmp);
  const prun = () => { try { execSync('bash verify.sh', { cwd: pdir, stdio: 'pipe' }); return 0; } catch (e) { return e.status; } };
  const pySeedRc = prun();                                                  // no answer yet -> FAIL (exit 2)
  fs.writeFileSync(path.join(pdir, 'out', 'answer.txt'), '42\n');
  const pyFixedRc = prun();                                                 // answered -> PASS (exit 0)
  const pyHidden = !fs.existsSync(path.join(pdir, 'check.py')) &&           // oracle not on disk
    !fs.readFileSync(path.join(pdir, 'verify.sh'), 'utf8').includes("read_text");  // source not inline-readable

  const ok = seedRc === 2 && fixedRc === 0 && shown && hidden &&
    pySeedRc === 2 && pyFixedRc === 0 && pyHidden;
  console.log(`selftest: emitted ${path.relative(tmp, dir)} | seed verify rc=${seedRc} (want 2) | fixed rc=${fixedRc} (want 0) | files ok=${shown && hidden}`);
  console.log(`selftest[check_py]: seed rc=${pySeedRc} (want 2) | fixed rc=${pyFixedRc} (want 0) | oracle hidden=${pyHidden}`);
  try { fs.rmSync(tmp, { recursive: true, force: true }); } catch {}
  if (!ok) { console.error('SELFTEST FAILED'); process.exit(1); }
  console.log('✓ import-task selftest passed — the Crucible task contract wraps an external instance end-to-end.');
  process.exit(0);
}

const inFile = arg('in'), outDir = arg('out');
if (!inFile || !outDir) { console.error('usage: import-task.js --in <instance.json> --out <tasks-dir>   |   --selftest'); process.exit(2); }
const instance = JSON.parse(fs.readFileSync(inFile, 'utf8'));
const dir = emitTask(instance, outDir);
console.log('wrote Crucible task -> ' + dir);

module.exports = { emitTask };
