#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (analyze-access-logs) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IHJlLCBwYXRobGliLCBzeXMKcCA9IHBhdGhsaWIuUGF0aCgncmVwb3J0LnR4dCcpCmlmIG5vdCBwLmV4aXN0cygpOiBwcmludCgncmVwb3J0LnR4dCBtaXNzaW5nJyk7IHN5cy5leGl0KDEpCmMgPSBwLnJlYWRfdGV4dCgpLnN0cmlwKCkKZGVmIG9uZShyeCwgbGFiZWwpOgogICAgbSA9IHJlLnNlYXJjaChyeCwgYywgcmUuTSkKICAgIGlmIG5vdCBtOiBwcmludCgnbWlzc2luZyBsaW5lOicsIGxhYmVsKTsgc3lzLmV4aXQoMSkKICAgIHJldHVybiBmbG9hdChtLmdyb3VwKDEpKQppZiBvbmUociJUb3RhbCByZXF1ZXN0czpccyooXGQrKD86XC5cZCspPykkIiwgIlRvdGFsIHJlcXVlc3RzIikgIT0gMjAwMDoKICAgIHByaW50KCd0b3RhbCByZXF1ZXN0cyB3cm9uZycpOyBzeXMuZXhpdCgxKQppZiBvbmUociJVbmlxdWUgSVAgYWRkcmVzc2VzOlxzKihcZCsoPzpcLlxkKyk/KSQiLCAiVW5pcXVlIElQcyIpICE9IDI3MzoKICAgIHByaW50KCd1bmlxdWUgaXBzIHdyb25nJyk7IHN5cy5leGl0KDEpCmlmIG9uZShyIjQwNCBlcnJvcnM6XHMqKFxkKyg/OlwuXGQrKT8pJCIsICI0MDQgZXJyb3JzIikgIT0gODM6CiAgICBwcmludCgnNDA0IGNvdW50IHdyb25nJyk7IHN5cy5leGl0KDEpCnVybF9saW5lcyA9IFtsIGZvciBsIGluIGMuc3BsaXRsaW5lcygpIGlmIHJlLmZ1bGxtYXRjaChyIlxzezJ9L1xTKzogXGQrIiwgbCldCmlmIGxlbih1cmxfbGluZXMpICE9IDM6IHByaW50KCduZWVkIGV4YWN0bHkgMyB0b3AgdXJsIGxpbmVzJyk7IHN5cy5leGl0KDEpCmlmIHtsLnN0cmlwKCkgZm9yIGwgaW4gdXJsX2xpbmVzfSAhPSB7Ii9vcmRlci1jb25maXJtYXRpb246IDU0IiwgIi9wcm9kdWN0LzQ1NjogNTMiLCAiL2Fib3V0Lmh0bWw6IDUyIn06CiAgICBwcmludCgndG9wIHVybHMgd3JvbmcnKTsgc3lzLmV4aXQoMSkKZm9yIHJ4LCBsYmwgaW4gWyhyIl5Ub3RhbCByZXF1ZXN0czpccypcZCsoPzpcLlxkKyk/JCIsICd0b3RhbCcpLAogICAgICAgICAgICAgICAgKHIiXlVuaXF1ZSBJUCBhZGRyZXNzZXM6XHMqXGQrKD86XC5cZCspPyQiLCAndW5pcXVlJyksCiAgICAgICAgICAgICAgICAociJeNDA0IGVycm9yczpccypcZCsoPzpcLlxkKyk/JCIsICc0MDQnKSwKICAgICAgICAgICAgICAgIChyIl5Ub3AgMyBVUkxzOiQiLCAnaGVhZGVyJyldOgogICAgaWYgbGVuKHJlLmZpbmRhbGwocngsIGMsIHJlLk0pKSAhPSAxOiBwcmludCgnZm9ybWF0OiBleHBlY3RlZCBleGFjdGx5IG9uZScsIGxibCk7IHN5cy5leGl0KDEpCnN5cy5leGl0KDApCg==
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import re' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
