#!/usr/bin/env node
// make-figs.js — regenerate the paper's figure data from the frozen run ledgers.
//
// Fig (a) codex-bookend.dat — the interface-fit discontinuity: codex finished-cell pass rate
//   per model. The local census (144 cells: pilot finished + qwen3.5-pilot + Phase D) matches
//   the running census in main.tex ("0/144 local cells"); the cloud column is the Phase B
//   bookend (20/20 on gpt-5.5). The qwen3.5 size-ladder ledger adds 54 more local zeros that
//   are NOT in the text census; they are asserted here but plotted only via the caption note.
//
// Fig (b) ladder.dat — Phase C size ladder: Goodput per harness across qwen3.5 {2b, 4b, 9b}
//   (Table 2 of the paper, drawn as curves).
//
// The script FAILS (exit 1) if any regenerated number no longer matches the census the paper
// text states — same contract as crucible/audit-claims.js: fix the paper, never the check.
//
// Usage: node paper/figs/make-figs.js          (writes paper/figs/*.dat)
//        node paper/figs/make-figs.js --check  (writes nothing; fails if committed .dat differ)
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const RESULTS = path.join(ROOT, 'crucible', 'results');
const load = f => fs.readFileSync(path.join(RESULTS, f), 'utf8')
  .split('\n').filter(Boolean).map(JSON.parse);
const die = msg => { console.error(`make-figs: ${msg}`); process.exit(1); };

// --- fig (a): codex finished cells per model, pilot + qwen3.5-pilot + Phase D + cloud bookend ---
// local cells from the three census ledgers; the cloud column from the Phase B bookend arm only
// (battery.published.jsonl also holds the 4 superseded 1-seed gpt-5.5 cells — not the 20/20 claim)
const censusRows = [
  ...[...load('battery.published.jsonl'), ...load('qwen35-pilot.jsonl'), ...load('phase-d-llama.jsonl')]
    .filter(r => r.model !== 'gpt-5.5'),
  ...load('cloud-b2.jsonl'),
].filter(r => r.adapter === 'codex' && !r.timed_out);
const MODELS = [                       // display order: locals by family, cloud last
  ['deepseek-r1:1.5b', 'local'], ['deepseek-r1:8b', 'local'], ['qwen3:8b', 'local'],
  ['qwen3.5:9b', 'local'], ['llama3.2:3b', 'local'], ['gpt-5.5', 'cloud'],
];
const cells = m => censusRows.filter(r => r.model === m);
const passed = rs => rs.filter(r => r.result === 'passed').length;
const localN = MODELS.filter(([, k]) => k === 'local')
  .reduce((s, [m]) => s + cells(m).length, 0);
const localP = MODELS.filter(([, k]) => k === 'local')
  .reduce((s, [m]) => s + passed(cells(m)), 0);
if (localN !== 144 || localP !== 0) die(`local census drifted: ${localP}/${localN}, paper says 0/144`);
if (cells('gpt-5.5').length !== 20 || passed(cells('gpt-5.5')) !== 20)
  die(`cloud bookend drifted: ${passed(cells('gpt-5.5'))}/${cells('gpt-5.5').length}, paper says 20/20`);
// the size-ladder ledger's extra codex zeros (outside the text census, cited in the caption)
const ladderCodex = load('qwen35-scaled.jsonl').filter(r => r.adapter === 'codex' && !r.timed_out);
if (passed(ladderCodex) !== 0) die(`size-ladder codex passed ${passed(ladderCodex)} cells — no longer a structural zero`);

const HDR = '% AUTO-GENERATED by paper/figs/make-figs.js from the frozen run ledgers — do not edit by hand.\n';
const rows = MODELS.map(([m, kind]) => {
  const rs = cells(m);
  return { m, kind, n: rs.length, p: passed(rs), rate: passed(rs) / rs.length };
});
const symb = rows.map(r => r.m).join(',');
const figA = HDR + `\\begin{tikzpicture}
\\begin{axis}[
  width=\\linewidth, height=4.8cm,
  ybar, bar width=13pt, bar shift=0pt,
  ymin=0, ymax=1.18, ytick={0,0.5,1},
  ylabel={\\small pass rate (finished cells)},
  symbolic x coords={${symb}},
  xtick={${symb}},
  xticklabel style={rotate=30, anchor=north east, font=\\scriptsize\\ttfamily},
  axis line style={draw=gray!60}, tick style={draw=gray!60},
  ymajorgrids, grid style={gray!20},
  clip=false,
]
\\addplot[ybar, fill=gray!55, draw=none] coordinates {
${rows.filter(r => r.kind === 'local').map(r => `  (${r.m},${r.rate.toFixed(3)})`).join('\n')}
};
\\addplot[ybar, fill=figblue, draw=none] coordinates {
${rows.filter(r => r.kind === 'cloud').map(r => `  (${r.m},${r.rate.toFixed(3)})`).join('\n')}
};
${rows.map(r => `\\node[above, font=\\scriptsize${r.kind === 'cloud' ? '\\bfseries' : ''}] at (axis cs:${r.m},${r.rate.toFixed(3)}) {${r.p}/${r.n}};`).join('\n')}
\\end{axis}
\\end{tikzpicture}
`;

// --- fig (b): Phase C qwen3.5 size-ladder Goodput curves (Table 2) ---
const scaled = load('qwen35-scaled.jsonl');
const goodput = rs => rs.length ? rs.reduce((s, r) => s + (r.timed_out ? 0 : (r.score ?? 0)), 0) / rs.length : NaN;
const HARNESSES = ['pi', 'ollama', 'aider', 'codex'];
const SIZES = [['qwen3.5:2b', 2], ['qwen3.5:4b', 4], ['qwen3.5:9b', 9]];
const gp = (a, m) => goodput(scaled.filter(r => r.adapter === a && r.model === m));
// pin the two numbers the paper's ladder claim leans on (Δ=0.55 on the 2b)
if (Math.round(gp('pi', 'qwen3.5:2b') * 100) / 100 !== 0.79 ||
    Math.round(gp('ollama', 'qwen3.5:2b') * 100) / 100 !== 0.24)
  die(`2b anchor drifted: pi=${gp('pi', 'qwen3.5:2b').toFixed(3)} ollama=${gp('ollama', 'qwen3.5:2b').toFixed(3)}, paper says 0.79/0.24`);

// series styling: Okabe–Ito hues (validated colorblind-safe), distinct marker + dash per
// series so identity never rides on color alone; direct end-labels instead of a legend box.
const STYLE = {
  pi:     { color: 'figblue',      mark: '*',         dash: 'solid' },
  ollama: { color: 'figvermilion', mark: 'square*',   dash: 'dashed' },
  aider:  { color: 'figgreen',     mark: 'triangle*', dash: 'solid' },
  codex:  { color: 'figpink',      mark: 'diamond*',  dash: 'dotted' },
};
const LABEL = { pi: 'pi', ollama: 'ollama (control)', aider: 'aider', codex: 'codex' };
const LABEL_POS = { pi: 0.07, ollama: -0.09, aider: -0.07, codex: 0.05 };  // offset from mid-line
const figB = HDR + `\\begin{tikzpicture}
\\begin{axis}[
  width=\\linewidth, height=4.8cm,
  xmin=1.4, xmax=9.4, ymin=-0.03, ymax=1.02,
  xtick={2,4,9}, xticklabels={2b (2.7\\,GB),4b (3.4\\,GB),9b (6.6\\,GB)},
  xticklabel style={font=\\scriptsize}, ytick={0,0.5,1},
  ylabel={\\small \\goodput{}},
  axis line style={draw=gray!60}, tick style={draw=gray!60},
  ymajorgrids, grid style={gray!20},
  clip=false,
]
${HARNESSES.map(a => {
  const s = STYLE[a];
  const pts = SIZES.map(([m, x]) => `(${x},${gp(a, m).toFixed(3)})`).join(' ');
  // label centered at x=6.5 (midpoint of the 4b→9b segment), nudged off the line
  const yMid = (gp(a, 'qwen3.5:4b') + gp(a, 'qwen3.5:9b')) / 2 + LABEL_POS[a];
  return `\\addplot[${s.color}, ${s.dash}, thick, mark=${s.mark}, mark size=2.1pt, mark options={solid}] coordinates { ${pts} };
\\node[font=\\scriptsize, text=black!75] at (axis cs:6.5,${yMid.toFixed(3)}) {${LABEL[a]}};`;
}).join('\n')}
\\end{axis}
\\end{tikzpicture}
`;

// --- write / check ------------------------------------------------------------
const OUT = { 'codex-bookend.tex': figA, 'ladder.tex': figB };
const check = process.argv.includes('--check');
let stale = 0;
for (const [f, content] of Object.entries(OUT)) {
  const p = path.join(__dirname, f);
  if (check) {
    const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
    if (cur !== content) { console.error(`make-figs: ${f} is stale — regenerate with node paper/figs/make-figs.js`); stale++; }
  } else {
    fs.writeFileSync(p, content);
    console.log(`wrote paper/figs/${f}`);
  }
}
if (stale) process.exit(1);
console.log(`figure data ${check ? 'verified against' : 'regenerated from'} the frozen ledgers (codex local ${localP}/${localN}, +${ladderCodex.length} ladder zeros; cloud 20/20).`);
