#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (mahjong-winninghand) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IHJlLCBwYXRobGliLCBzeXMKcCA9IHBhdGhsaWIuUGF0aCgncmVzdWx0LnR4dCcpCmlmIG5vdCBwLmV4aXN0cygpOiBwcmludCgncmVzdWx0LnR4dCBtaXNzaW5nJyk7IHN5cy5leGl0KDEpCmV4cGVjdGVkID0gewogICAgImhhbmRfMDAxLmpzb24iOiB7Ildpbm5pbmcgaGFuZCAtIFNldmVuIFBhaXJzIiwgIldpbm5pbmcgaGFuZCAtIFN0YW5kYXJkIn0sCiAgICAiaGFuZF8wMDQuanNvbiI6IHsiV2lubmluZyBoYW5kIC0gU2V2ZW4gUGFpcnMifSwKICAgICJoYW5kXzAwNS5qc29uIjogeyJXaW5uaW5nIGhhbmQgLSBTZXZlbiBQYWlycyIsICJXaW5uaW5nIGhhbmQgLSBTdGFuZGFyZCJ9LAogICAgImhhbmRfMDA3Lmpzb24iOiB7Ildpbm5pbmcgaGFuZCAtIFNldmVuIFBhaXJzIiwgIldpbm5pbmcgaGFuZCAtIFN0YW5kYXJkIn0sCiAgICAiaGFuZF8wMDIuanNvbiI6IHsiV2lubmluZyBoYW5kIC0gVGhpcnRlZW4gT3JwaGFucyJ9LAogICAgImhhbmRfMDA2Lmpzb24iOiB7Ildpbm5pbmcgaGFuZCAtIFN0YW5kYXJkIn0sCiAgICAiaGFuZF8wMDguanNvbiI6IHsiV2lubmluZyBoYW5kIC0gU2V2ZW4gUGFpcnMifSwKICAgICJoYW5kXzAwMy5qc29uIjogeyJOb3QgYSB3aW5uaW5nIGhhbmQifSwKfQpnb3QgPSB7fQpmb3IgbGluZSBpbiBwLnJlYWRfdGV4dCgpLnN0cmlwKCkuc3BsaXQoJ1xuJyk6CiAgICBsaW5lID0gbGluZS5zdHJpcCgpCiAgICBpZiBub3QgbGluZSBvciAnOicgbm90IGluIGxpbmU6IGNvbnRpbnVlCiAgICBmbiwgcmlnaHQgPSBsaW5lLnNwbGl0KCc6JywgMSkKICAgIGZuID0gZm4uc3RyaXAoKTsgcmlnaHQgPSByaWdodC5zdHJpcCgpCiAgICBtID0gcmUuZmluZGFsbChyJyIoW14iXSspIicsIHJpZ2h0KQogICAgZ290W2ZuXSA9IHNldChtKSBpZiBtIGVsc2Uge3JpZ2h0fQppZiBsZW4oZ290KSAhPSBsZW4oZXhwZWN0ZWQpOiBwcmludCgnY291bnQgbWlzbWF0Y2gnLCBsZW4oZ290KSwgJ3ZzJywgbGVuKGV4cGVjdGVkKSk7IHN5cy5leGl0KDEpCmZvciBmbiwgZXhwIGluIGV4cGVjdGVkLml0ZW1zKCk6CiAgICBpZiBmbiBub3QgaW4gZ290OiBwcmludCgnbWlzc2luZycsIGZuKTsgc3lzLmV4aXQoMSkKICAgIGlmIGdvdFtmbl0gIT0gZXhwOiBwcmludCgnbWlzbWF0Y2gnLCBmbiwgZ290W2ZuXSwgJ3ZzJywgZXhwKTsgc3lzLmV4aXQoMSkKc3lzLmV4aXQoMCkK
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import re' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
