#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (hello-world) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IHBhdGhsaWIsIHN5cwpwID0gcGF0aGxpYi5QYXRoKCdoZWxsby50eHQnKQppZiBub3QgcC5leGlzdHMoKTogcHJpbnQoJ2hlbGxvLnR4dCBkb2VzIG5vdCBleGlzdCcpOyBzeXMuZXhpdCgxKQpzeXMuZXhpdCgwIGlmIHAucmVhZF90ZXh0KCkuc3RyaXAoKSA9PSAnSGVsbG8sIHdvcmxkIScgZWxzZSAxKQo=
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import pathlib' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
