#!/usr/bin/env bash
# generated by import-task.js from Terminal-Bench (fix-permissions) — deterministic oracle.
set -uo pipefail
cd "$(dirname "$0")"
SRC=$(cat <<'__B64__'
aW1wb3J0IG9zLCBzdGF0LCBzdWJwcm9jZXNzLCBzeXMKcyA9ICdwcm9jZXNzX2RhdGEuc2gnCmlmIG5vdCBvcy5wYXRoLmV4aXN0cyhzKTogcHJpbnQoJ3Byb2Nlc3NfZGF0YS5zaCBtaXNzaW5nJyk7IHN5cy5leGl0KDEpCmlmIG5vdCAob3Muc3RhdChzKS5zdF9tb2RlICYgc3RhdC5TX0lYVVNSKTogcHJpbnQoJ3Byb2Nlc3NfZGF0YS5zaCBub3QgZXhlY3V0YWJsZScpOyBzeXMuZXhpdCgxKQpyID0gc3VicHJvY2Vzcy5ydW4oWycuLycgKyBzXSwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlKQppZiByLnJldHVybmNvZGUgIT0gMDogcHJpbnQoJ3NjcmlwdCBleGl0ZWQnLCByLnJldHVybmNvZGUpOyBzeXMuZXhpdCgxKQpzeXMuZXhpdCgwIGlmICdEYXRhIHByb2Nlc3NlZCBzdWNjZXNzZnVsbHkhJyBpbiByLnN0ZG91dCBlbHNlIDEpCg==
__B64__
)
PYBIN=""
for c in python3 python; do command -v "$c" >/dev/null 2>&1 || continue; "$c" -c 'import os' >/dev/null 2>&1 && { PYBIN="$c"; break; }; done
[ -n "$PYBIN" ] || { echo "no python3 with required modules on PATH" >&2; exit 2; }
OUT="$(printf '%s' "$SRC" | base64 --decode | "$PYBIN" - 2>&1)"; rc=$?
if [ "$rc" -eq 0 ]; then exit 0; fi
echo "external oracle failing (rc=$rc):" >&2
printf '%s\n' "$OUT" | tail -25 >&2
exit 2
