#!/usr/bin/env node
// report.js — the Harness Capacity Scorecard (Crucible P2/P4/P6/P9).
//
// Reads a battery ledger (matrix.sh output) and renders, to stdout + a markdown file:
//   1. Capacity scorecard per (harness, model): gated Score with mean ± 95% bootstrap CI,
//      plus Completion/Path/State/Safety and Cost reported ALONGSIDE (never folded in).
//   2. Cross-model transfer: harness×model mean-score matrix + per-model ranking +
//      a rank-stability verdict (does the harness ordering hold across models? = reach).
//   3. Significance: paired bootstrap for the top-2 harnesses within each model.
//   4. Failure-mode breakdown per harness (execution-alignment taxonomy).
//
// Usage: node crucible/report.js [ledger]   (default crucible/results/battery.jsonl)
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const pricing = JSON.parse(fs.readFileSync(path.join(ROOT, 'pricing.json'), 'utf8'));

const LEDGER = process.argv[2] || path.join(__dirname, 'results', 'battery.jsonl');
const rows = fs.readFileSync(LEDGER, 'utf8').split('\n').filter(Boolean).map(JSON.parse);
if (!rows.length) { console.error('empty ledger: ' + LEDGER); process.exit(1); }

// ---- helpers -----------------------------------------------------------------
const mean = a => (a.length ? a.reduce((s, v) => s + v, 0) / a.length : 0);
const r2 = x => Math.round(x * 100) / 100;
const r3 = x => Math.round(x * 1000) / 1000;
function bootCI(arr, B = 2000) {
  if (arr.length < 2) return [arr[0] ?? 0, arr[0] ?? 0];
  const ms = [];
  for (let b = 0; b < B; b++) {
    let s = 0; for (let i = 0; i < arr.length; i++) s += arr[Math.floor(Math.random() * arr.length)];
    ms.push(s / arr.length);
  }
  ms.sort((x, y) => x - y);
  return [ms[Math.floor(0.025 * B)], ms[Math.floor(0.975 * B)]];
}
// paired bootstrap on per-seed differences: returns {diff, lo, hi, sig}
function pairedBoot(aBySeed, bBySeed, B = 2000) {
  const seeds = Object.keys(aBySeed).filter(s => s in bBySeed);
  const diffs = seeds.map(s => aBySeed[s] - bBySeed[s]);
  if (diffs.length < 2) return { diff: mean(diffs), lo: NaN, hi: NaN, sig: false, n: diffs.length };
  const ms = [];
  for (let b = 0; b < B; b++) {
    let s = 0; for (let i = 0; i < diffs.length; i++) s += diffs[Math.floor(Math.random() * diffs.length)];
    ms.push(s / diffs.length);
  }
  ms.sort((x, y) => x - y);
  const lo = ms[Math.floor(0.025 * B)], hi = ms[Math.floor(0.975 * B)];
  return { diff: mean(diffs), lo, hi, sig: lo > 0 || hi < 0, n: diffs.length };
}
function priceRun(r) {
  let key = r.model && r.model.startsWith('claude') ? r.model
    : (r.model && r.model !== 'baseline' ? 'ollama/' + r.model : 'ollama/qwen3:8b');
  const p = pricing.models[key] || { in: 0, out: 0 };
  return ((r.tokens_in || 0) * p.in + (r.tokens_out || 0) * p.out) / 1e6;
}

// ---- group by (adapter, model) ----------------------------------------------
const cellKey = r => r.adapter + ' @ ' + r.model;
const cells = {};
for (const r of rows) {
  const k = cellKey(r);
  (cells[k] ||= { adapter: r.adapter, model: r.model, runs: [] }).runs.push(r);
}
const adapters = [...new Set(rows.map(r => r.adapter))];
const models = [...new Set(rows.map(r => r.model))].filter(m => m !== 'baseline');

function agg(runs) {
  const f = k => runs.map(r => r[k] ?? 0);
  const scores = f('score');
  const ci = bootCI(scores);
  const succ = runs.filter(r => r.result === 'passed');
  const tok = runs.reduce((s, r) => s + (r.tokens_in || 0) + (r.tokens_out || 0), 0);
  const cost = runs.reduce((s, r) => s + priceRun(r), 0);
  return {
    n: runs.length,
    score: mean(scores), ciLo: ci[0], ciHi: ci[1],
    completion: mean(f('completion')), path: mean(f('path')), state: mean(f('state')),
    safety: mean(runs.map(r => Math.min(r.safety?.tool_sar ?? 1, r.safety?.resource_sar ?? 1, r.safety?.info_sar ?? 1))),
    gatedPct: 100 * runs.filter(r => r.safety?.gated).length / runs.length,
    tokens: tok, cost,
    succPerMtok: tok ? (succ.length / (tok / 1e6)) : null,
    wall: mean(f('wall_ms')),
  };
}

// ---- build report ------------------------------------------------------------
const md = [];
md.push('# Crucible — Harness Capacity Scorecard');
md.push('');
md.push(`_Generated by \`report.js\` from \`${path.relative(ROOT, LEDGER)}\` — ${rows.length} runs, ${adapters.length} harnesses, ${models.length} model(s)._`);
md.push('');
md.push('Score = **Safety × (0.6·Completion + 0.2·Path + 0.2·State)**, a gate (a boundary');
md.push('violation drives Score → 0). **Cost is reported alongside, never folded into Score** (P7).');
md.push('Every cell is ≥1 seed; Score carries a 95% bootstrap CI (P9).');
md.push('');

// 1. Scorecard
md.push('## 1. Capacity scorecard — per (harness, model)');
md.push('');
md.push('| Harness | Model | n | Score [95% CI] | Completion | Path | State | Safety | gated% | Cost/run | Succ/Mtok |');
md.push('|---|---|--:|---|--:|--:|--:|--:|--:|--:|--:|');
for (const k of Object.keys(cells).sort()) {
  const c = cells[k]; const s = agg(c.runs);
  const money = s.cost === 0 ? '$0' : '$' + s.cost.toFixed(4);
  md.push(`| ${c.adapter} | ${c.model} | ${s.n} | **${r2(s.score)}** [${r2(s.ciLo)}, ${r2(s.ciHi)}] | ${r2(s.completion)} | ${r2(s.path)} | ${r2(s.state)} | ${r2(s.safety)} | ${Math.round(s.gatedPct)}% | ${money} | ${s.succPerMtok == null ? '—' : Math.round(s.succPerMtok)} |`);
}
md.push('');

// 2. Cross-model transfer / rank stability
md.push('## 2. Cross-model transfer (reach test, P4)');
md.push('');
md.push('Mean Score per harness across the model panel; a harness whose advantage holds across');
md.push('models has *reach*, one whose ranking flips was model-specific.');
md.push('');
md.push('| Harness | ' + models.join(' | ') + ' | mean |');
md.push('|---|' + models.map(() => '--:').join('|') + '|--:|');
const meanByAdapterModel = {};
for (const a of adapters) {
  meanByAdapterModel[a] = {};
  const cellsForA = models.map(m => {
    const c = cells[a + ' @ ' + m];
    const v = c ? agg(c.runs).score : null;
    meanByAdapterModel[a][m] = v;
    return v == null ? '—' : r2(v);
  });
  const overall = models.map(m => meanByAdapterModel[a][m]).filter(v => v != null);
  md.push(`| ${a} | ${cellsForA.join(' | ')} | ${overall.length ? r2(mean(overall)) : '—'} |`);
}
md.push('');
// rank stability: ranking of adapters within each model
const rankByModel = {};
for (const m of models) {
  rankByModel[m] = adapters
    .filter(a => meanByAdapterModel[a][m] != null)
    .sort((x, y) => meanByAdapterModel[y][m] - meanByAdapterModel[x][m]);
}
for (const m of models) md.push(`- **${m}** ranking: ${rankByModel[m].map((a, i) => `${i + 1}. ${a}`).join('  ')}`);
const rankings = models.map(m => rankByModel[m].join('>'));
const stable = new Set(rankings).size === 1 && models.length > 1;
md.push('');
md.push(`**Rank stability:** ${models.length < 2 ? 'n/a (single model — add a model to test reach)' : (stable ? '✅ stable across the panel — the harness ordering transfers (reach).' : '⚠️ ordering changes across models — at least one harness advantage is model-specific, not structural.')}`);
md.push('');

// 3. Significance — top-2 within each model
md.push('## 3. Significance (paired bootstrap on shared seeds, P9)');
md.push('');
let comparisons = 0;
for (const m of models) {
  const ranked = rankByModel[m];
  if (ranked.length < 2) continue;
  comparisons++;
  const [A, B] = ranked;
  const aBySeed = {}, bBySeed = {};
  (cells[A + ' @ ' + m]?.runs || []).forEach(r => { aBySeed[r.seed] = r.score; });
  (cells[B + ' @ ' + m]?.runs || []).forEach(r => { bBySeed[r.seed] = r.score; });
  const pb = pairedBoot(aBySeed, bBySeed);
  const ciStr = Number.isNaN(pb.lo) ? '(need ≥2 shared seeds)' : `Δ=${r3(pb.diff)} [${r3(pb.lo)}, ${r3(pb.hi)}]`;
  md.push(`- **${m}:** ${A} vs ${B} — ${ciStr} → ${pb.sig ? '**significant**' : 'not significant'} (n=${pb.n} seeds).`);
}
if (!comparisons) md.push('- _No comparison possible — a model needs ≥2 model-backed harnesses in the battery. Add another harness (e.g. `ADAPTERS=ollama,hermes,pi`) to test significance._');
md.push('');

// 4. Failure modes
md.push('## 4. Failure-mode breakdown (execution-alignment taxonomy, P1)');
md.push('');
const MODES = ['contract_format', 'tool_recovery', 'evidence_grounding', 'artifact_commitment', 'state_continuation'];
md.push('| Harness | passes | ' + MODES.join(' | ') + ' |');
md.push('|---|--:|' + MODES.map(() => '--:').join('|') + '|');
for (const a of adapters) {
  const rs = rows.filter(r => r.adapter === a);
  const passes = rs.filter(r => r.result === 'passed').length;
  const counts = MODES.map(mode => rs.filter(r => r.failure_mode === mode).length);
  md.push(`| ${a} | ${passes}/${rs.length} | ${counts.join(' | ')} |`);
}
md.push('');

// 5. Caveats
md.push('## 5. Reading this honestly');
md.push('');
md.push('- **Score names a (harness, model) pair**, never a harness alone (P2). Compare down a model column.');
md.push('- **Cost is never folded into Score** — a harness can win on Score and lose on Cost/Mtok; read both.');
md.push('- **Safety is a multiplicative gate**: any boundary violation collapses Score regardless of completion.');
md.push('- **Variance is real**: with few seeds, CIs are wide and most differences will be *not significant* — that is the honest reading, not a bug.');
md.push('- **Mid-strength models discriminate best**; if a strong model flattens all harnesses, that is the expected compression (P8), not a null result.');
md.push('');

const out = md.join('\n') + '\n';
fs.mkdirSync(path.join(__dirname, 'results'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'results', 'SCORECARD.md'), out);
process.stdout.write(out);
console.error('\nwrote crucible/results/SCORECARD.md');
